### ISSUE TITLE
Text spacing incorrect on charts on Android mobile

### ISSUE THREAD

**Issue by shaahmad** [owid/owid-grapher#360]
On my Pixel 3, virtually all charts have text spacing issues when opened in the Google Search "browser" and Chrome Beta. Appears to happen on @MarcelGerber's phone as well.
![Screenshot_20200327-195856](https://user-images.githubusercontent.com/11683872/77809371-a62a0180-7065-11ea-8fc6-2af1c40fc1da.png)

**Comment by MarcelGerber** [comment]
Weird.
I am neither seeing these issues on my Android 10 phone, nor on my PC.

Which browser are you using? Chrome?
Can you try viewing https://ourworldindata.org/exports/life-expectancy_v21_850x600.svg in there, that should be the exact graphic that's shown in your screenshot above. Also, do you see issues on https://ourworldindata.org/grapher/life-expectancy itself, too, or only for the chart preview?

**Comment by shaahmad** [comment]
Weirdly, the issue has also stopped on my phone, but had been there for least a week beforehand. I'll keep checking over the next couple weeks and will close this issue if it doesn't return.

**Comment by MarcelGerber** [comment]
Hm. I'd guess some browser or device update has fixed this issue in the meantime.

I'm closing this issue for now, but feel free to reopen if you experience this issue again.

**Comment by shaahmad** [comment]
Issue appearing for both of us, details noted in initial description.

**Comment by MarcelGerber** [comment]
Yep, as @shaahmad pointed out I'm now seeing this too, using Chrome Beta (83.0.4103.23) on Android.

One thing to note is:
* This is happening for embedded svg previews into a post/entry, e.g. in https://ourworldindata.org/life-expectancy
* It's not happening in interactive charts
* It's also not present when viewing an embedded svg chart directly, e.g. https://ourworldindata.org/exports/life-expectancy-a42c8357c168ebd03c90930b9d3c439b_v21_850x600.svg

**Comment by danielgavrilov** [comment]
Likely something to do with webfonts?

Embedded SVG previews load in an environment where we have either fetched or are fetching the necessary webfonts (Playfair Display and Lato), whereas standalone SVGs will use a fallback available on the system.

**Comment by danielgavrilov** [comment]
To render SVGs consistently across browsers we need to either:
1. [Load the webfonts within each SVG file](https://graphicdesign.stackexchange.com/a/5167)
2. Convert the `<text>` into vector shapes server-side (I think this might increase the SVG size significantly?)

**Comment by MarcelGerber** [comment]
No, pretty sure this is just some Chrome bug, which is caused by the `.article-content figure[data-grapher-src] img` rule which sets `width: 100%`.
I have found two potential fixes:
* Setting `width` to anything that results in one pixel less, like `width: 99.9%`
* Setting `padding-left: 1px` (margin, padding-top don't work)

Will experiment a little more to see if there's an "even more invisible" solution I can come up with 😄

**Comment by MarcelGerber** [comment]
Okay, turns out to be not-so-easy. Setting the `width` helped before, but now it doesn't any more (guess it only forced a re-render anyway).
I too think this is related to web fonts, and is not easy too fix. I still think this is inherently a Chrome bug and not intended behaviour.

**Comment by danielgavrilov** [comment]
Ha, interesting that a re-render fixes it! Maybe we could do the lazy loading you suggested some time ago? Not a definite solution but maybe it will cause a long enough delay for the font to load?

**Comment by MarcelGerber** [comment]
No, a re-render doesn't fix it consistently.

But I've been able to trim this all down to a very minimal reproducible demo, and have filed a bug with the Chrome team: https://bugs.chromium.org/p/chromium/issues/detail?id=1074416
Let's see what they have to say.

**Comment by danielgavrilov** [comment]
@MarcelGerber Awesome that you opened that you filed that bug! Thanks a lot!

It seems [someone responded](https://bugs.chromium.org/p/chromium/issues/detail?id=1074416#c3):
> This sounds like it could have a similar root cause as issue 670672 - does adding "text-rendering: geometricPrecision" to the <text> element (or one of its ancestors) help/have any effect?

**Comment by MarcelGerber** [comment]
@danielgavrilov Yes, I've tried that and setting `text-rendering: geometricPrecision` indeed fixes this issue!

We can easily switch over to `geometricPrecision` for our code (we currently have `optimizeLegibility`), but to have it correct for old exports we'd probably need another "svg migration" task...

**Comment by danyx23** [comment]
@MarcelGerber I just tried this on my android phone in an in-app browser and it looks like this issue is resolved - can you verify this?

**Comment by MarcelGerber** [comment]
No, it's still an issue for me.
For example, this is https://ourworldindata.org/co2-and-other-greenhouse-gas-emissions in the Slack in-app browser:
![Screenshot_20210707-083532.jpg](https://user-images.githubusercontent.com/2641501/124711469-699eb400-defe-11eb-956d-46698532d14f.jpg)

**Comment by danyx23** [comment]
I checked and realized that I had set firefox as my default browser - after switching to Chrome it is broken again so upstream bug persists.

**Comment by MarcelGerber** [comment]
> I checked and realized that I had set firefox as my default browser - after switching to Chrome it is broken again so upstream bug persists.

Yes - maybe using `text-rendering: geometricPrecision` to our SVG exports would be a good fix?

**Comment by danyx23** [comment]
@MarcelGerber yes I think we should do this. Having such weird text rendering is pretty annoying and it seems like this is not enough of a priority upstream to fix it anytime soon. Do you have an idea where to add this property? Every text instance in the export?

**Comment by MarcelGerber** [comment]
We already set the exported SVG to be in `optimizeLegibility` mode here (and I don't quite know why?):
https://github.com/owid/owid-grapher/blob/2e05034521cde8bd40ddefb95b1bbe62e540b666/grapher/captionedChart/CaptionedChart.tsx#L347

So, we could change that over to `geometricPrecision` which should resolve this issue. This will however only affect newly-generated SVG exports; to do the same for existing ones we would also need to run a `s/optimizeLegibility/geometricPrecision/` replace in `owid-static`.

**Comment by danielgavrilov** [comment]
(Just sharing this from our meeting today.)

To regenerate the SVGs, you can just delete:

- `/exports/*.svg` – this contains the **SVGs that are embedded in articles**. 

    - **These are the SVGs showing up on mobile browsers**, because on mobile we don't load the interactive chart embeds, unless the user visits an individual chart page.
    - In the filenames, they contain a version number, pixel dimensions and md5 hash of the query parameters (if they are changed from the defaults). Example: `weekly-icu-admissions-covid-a12e9e4f79c8fdab6f5e67fe666e4232_v172_850x600.svg`. 
    - Note **there are no PNG exports** in this folder.

- `/grapher/exports/*.(svg|png)` – this contains the SVGs and PNGs of individual charts, with default query parameters.

    - They are used as **social media images** (PNG), and placeholders in case the interactive chart fails to load (SVG).

**Comment by MarcelGerber** [comment]
After a long time, this is now finally fixed for good!
