### ISSUE TITLE
Decrease unnecessary padding in HeightedLegend

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#404]
As it has come up in both #403 and #393, there can be some dead space on the right of the legend in line and area charts:

![](https://user-images.githubusercontent.com/1308115/78711983-cc765980-790f-11ea-96d2-d8da5e958bb5.png)

There is big empty padding on the right of the label so that there is space for these marker lines, if they appear: 

![](https://user-images.githubusercontent.com/1308115/78713025-7e625580-7911-11ea-9a2b-75d36ac8f30b.png)

The space allocation for the legend is made in `HeightedLegend` _before_ we know whether we need marker lines. We need to shift this logic around so that we use the space fully.

**Comment by breck7** [comment]
I believe this was fixed? Closing.

**Comment by danielgavrilov** [comment]
It's not fixed yet, but step 1 is probably to create a story to make it easily reproducible.

Here's the same chart as above:

https://user-images.githubusercontent.com/1308115/103680806-9c331880-4f7e-11eb-8ffc-016212844eec.mov

When the connecting lines disappear, they move closer towards the chart and that introduces some unused space on the right.
